title: Made By Douglas # your site title
author: madebydouglas
email: madebydouglas@gmail.com # email for form submission, you also have to change it in _js/scripts.js
description: > # this means to ignore newlines until "baseurl:"
    Believer, designer, developer. Passionate about making insanely great things.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://madebydouglas.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: madebydouglas # replace with your_twitter_username or comment to remove link from footer
github_username:  madebydouglas # replace with your_github_username or comment to remove link from footer
# instagram_username: madebydouglas # replace with your_instagram_username or comment to remove link from footer
social:
  name: Douglas Hewitt
  links:
    - https://twitter.com/madebydouglas
    - https://www.facebook.com/madebydouglas
    - https://www.linkedin.com/in/madebydouglas
    - https://plus.google.com/+madebydouglas
    - https://github.com/madebydouglas
    - https://keybase.io/madebydouglas

disqus:
  shortname: madebydouglas # to enable comments replace with your_disqus_shortname

# Build settings
markdown: kramdown
highlighter: rouge # or pygments or null
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
